---
- hosts: servers
  become: yes
  become_user: root
  vars_files:
    - vars/vars.yaml
  roles:
    - tools
    - docker
    - docker-compose
    - uashield
  handlers:
    - include: handlers/main.yml
