# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# How many threads do we use?
threadsCount: 256

# Do we want to enable proxy? (true|false)
useProxy: false

# How many pods do we want to run?
replicaCount: 1

image:
  repository: ghcr.io/opengs/uashield
  pullPolicy: IfNotPresent
  # We can find a tag here: https://github.com/opengs/uashield/pkgs/container/uashield
  tag: "master"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1
  #   memory: 1Gi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
