- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Check if git is already present.
  command: which git
  failed_when: false
  changed_when: false
  register: git_command_result

- name: Install git
  apt:
    name: git
    state: latest
  when: git_command_result.rc == 1
