name: Node CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: wine install
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine32
          sudo snap install snapcraft --classic
      - name: Linux 64 bit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          rm -rf dist/
          npm install -g @quasar/cli yarn --force
          yarn install
          quasar build --mode electron --publish always -T linux
      - name: Linux 32bit
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T linux --arch ia32
      - name: Windows 64bit and 32bit 
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T win
      - name: Linux armv7l
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T linux --arch armv7l
      - name: Linux arm64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          quasar build --mode electron --publish always -T linux --arch arm64
